spring.application.name=FirstSpringBootApplication

spring.datasource.url=jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Gère la structure des tables (création/maj)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#on désactive le show-sql pour éviter de polluer les logs et pour des raisons de sécurité/performance.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.port=8000
